# Generated by Django 3.1.1 on 2020-09-09 10:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(editable=False, verbose_name='added date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=245, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('unique_code', models.CharField(blank=True, db_index=True, default='', max_length=9, unique=True, verbose_name='unique code')),
                ('code', models.CharField(blank=True, default='', max_length=250, verbose_name='code')),
                ('short_content', models.TextField(blank=True, default='', help_text='you can give short information.', max_length=250, verbose_name='short content')),
                ('content', models.TextField(blank=True, default='', verbose_name='content')),
                ('meta_title', models.CharField(db_index=True, max_length=245, unique=True, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, default='', max_length=245, verbose_name='meta description')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='publish date')),
                ('unpublish_at', models.DateTimeField(blank=True, null=True, verbose_name='unpublish date')),
                ('is_published', models.BooleanField(default=False, editable=False, verbose_name='is published')),
                ('long_name', models.CharField(blank=True, default='', max_length=250, verbose_name='long name')),
                ('place_type', models.CharField(choices=[('WOR', 'World'), ('INT', 'International Region'), ('COU', 'Country'), ('SC1', 'SubCountry 1'), ('SC2', 'SubCountry 2'), ('SC3', 'SubCountry 3'), ('SC4', 'SubCountry 4')], db_index=True, max_length=3, verbose_name='place type')),
                ('geo_name_id', models.PositiveIntegerField(blank=True, default=0, help_text='from geonames.org', verbose_name='geo name id')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='longitude')),
                ('water_area', models.FloatField(blank=True, default=0.0, help_text='km2', verbose_name='water area')),
                ('land_area', models.FloatField(blank=True, default=0.0, help_text='km2', verbose_name='land area')),
                ('area', models.FloatField(blank=True, default=0.0, help_text='km2', verbose_name='total area')),
                ('added_by', models.ForeignKey(blank=True, default=None, help_text='User who added the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places_continent_adders', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('updated_by', models.ForeignKey(blank=True, default=None, help_text='User who updated the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places_continent_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Continent',
                'verbose_name_plural': 'Continents',
                'ordering': ('id',),
            },
        ),
    ]
