# Generated by Django 3.1.1 on 2020-09-22 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('politics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(editable=False, verbose_name='added date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='updated date')),
                ('year', models.SmallIntegerField(verbose_name='year')),
                ('change', models.IntegerField(blank=True, null=True, verbose_name='change')),
                ('change_rate', models.FloatField(blank=True, null=True, verbose_name='change %')),
                ('fertility_rate', models.FloatField(blank=True, null=True, verbose_name='fertility')),
                ('median_age', models.FloatField(blank=True, null=True, verbose_name='median age')),
                ('density', models.FloatField(blank=True, null=True, verbose_name='density')),
                ('female', models.BigIntegerField(blank=True, null=True, verbose_name='female')),
                ('male', models.BigIntegerField(blank=True, null=True, verbose_name='male')),
                ('total', models.BigIntegerField(blank=True, null=True, verbose_name='total')),
                ('added_by', models.ForeignKey(blank=True, default=None, help_text='User who added the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_worldpopulation_adders', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldpopulation', to='sources.source', verbose_name='source')),
                ('updated_by', models.ForeignKey(blank=True, default=None, help_text='User who updated the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_worldpopulation_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'World Population',
                'verbose_name_plural': 'World Population',
                'unique_together': {('year', 'source')},
            },
        ),
        migrations.CreateModel(
            name='WorldGdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(editable=False, verbose_name='added date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='updated date')),
                ('year', models.SmallIntegerField(verbose_name='year')),
                ('change', models.IntegerField(blank=True, null=True, verbose_name='growth')),
                ('change_rate', models.FloatField(blank=True, null=True, verbose_name='growth %')),
                ('change_percapita', models.IntegerField(blank=True, null=True, verbose_name='growth per capita')),
                ('change_rate_percapita', models.FloatField(blank=True, null=True, verbose_name='growth % per capita')),
                ('gdp_ppp_constant_2017', models.BigIntegerField(blank=True, null=True, verbose_name='GDP, PPP (constant 2017 international $)')),
                ('gdp_ppp_current', models.BigIntegerField(blank=True, null=True, verbose_name='GDP, PPP (current international $)')),
                ('gdp_constant_2010', models.BigIntegerField(blank=True, null=True, verbose_name='GDP (constant 2010 US$)')),
                ('gdp_current', models.BigIntegerField(blank=True, null=True, verbose_name='GDP (current US$)')),
                ('gdp_percapita_ppp_constant_2017', models.BigIntegerField(blank=True, null=True, verbose_name='GDP per capita, PPP (constant 2017 international $)')),
                ('gdp_percapita_ppp_current', models.BigIntegerField(blank=True, null=True, verbose_name='GDP per capita, PPP (current international $)')),
                ('gdp_percapita_constant_2010', models.BigIntegerField(blank=True, null=True, verbose_name='GDP per capita (constant 2010 US$)')),
                ('gdp_percapita_current', models.BigIntegerField(blank=True, null=True, verbose_name='GDP per capita (current US$)')),
                ('added_by', models.ForeignKey(blank=True, default=None, help_text='User who added the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_worldgdp_adders', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldgdp', to='sources.source', verbose_name='source')),
                ('updated_by', models.ForeignKey(blank=True, default=None, help_text='User who updated the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_worldgdp_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'World GDP',
                'verbose_name_plural': 'World GDP',
                'unique_together': {('year', 'source')},
            },
        ),
        migrations.CreateModel(
            name='InternationalOrganizationPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(editable=False, verbose_name='added date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='updated date')),
                ('year', models.SmallIntegerField(verbose_name='year')),
                ('change', models.IntegerField(blank=True, null=True, verbose_name='change')),
                ('change_rate', models.FloatField(blank=True, null=True, verbose_name='change %')),
                ('fertility_rate', models.FloatField(blank=True, null=True, verbose_name='fertility')),
                ('median_age', models.FloatField(blank=True, null=True, verbose_name='median age')),
                ('density', models.FloatField(blank=True, null=True, verbose_name='density')),
                ('female', models.BigIntegerField(blank=True, null=True, verbose_name='female')),
                ('male', models.BigIntegerField(blank=True, null=True, verbose_name='male')),
                ('total', models.BigIntegerField(blank=True, null=True, verbose_name='total')),
                ('added_by', models.ForeignKey(blank=True, default=None, help_text='User who added the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_internationalorganizationpopulation_adders', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='politics.internationalorganization', verbose_name='organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internationalorganizationpopulation', to='sources.source', verbose_name='source')),
                ('updated_by', models.ForeignKey(blank=True, default=None, help_text='User who updated the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_internationalorganizationpopulation_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'International Organization Population',
                'verbose_name_plural': 'International Organization Populations',
                'unique_together': {('organization', 'year', 'source')},
            },
        ),
        migrations.CreateModel(
            name='CountryPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(editable=False, verbose_name='added date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='updated date')),
                ('year', models.SmallIntegerField(verbose_name='year')),
                ('change', models.IntegerField(blank=True, null=True, verbose_name='change')),
                ('change_rate', models.FloatField(blank=True, null=True, verbose_name='change %')),
                ('fertility_rate', models.FloatField(blank=True, null=True, verbose_name='fertility')),
                ('median_age', models.FloatField(blank=True, null=True, verbose_name='median age')),
                ('density', models.FloatField(blank=True, null=True, verbose_name='density')),
                ('female', models.IntegerField(blank=True, null=True, verbose_name='female')),
                ('male', models.IntegerField(blank=True, null=True, verbose_name='male')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='total')),
                ('added_by', models.ForeignKey(blank=True, default=None, help_text='User who added the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_countrypopulation_adders', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='places.country', verbose_name='country')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countrypopulation', to='sources.source', verbose_name='source')),
                ('updated_by', models.ForeignKey(blank=True, default=None, help_text='User who updated the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_countrypopulation_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Country Population',
                'verbose_name_plural': 'Country Populations',
                'unique_together': {('country', 'year', 'source')},
            },
        ),
        migrations.CreateModel(
            name='CountryGdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(editable=False, verbose_name='added date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='updated date')),
                ('year', models.SmallIntegerField(verbose_name='year')),
                ('change', models.IntegerField(blank=True, null=True, verbose_name='growth')),
                ('change_rate', models.FloatField(blank=True, null=True, verbose_name='growth %')),
                ('change_percapita', models.IntegerField(blank=True, null=True, verbose_name='growth per capita')),
                ('change_rate_percapita', models.FloatField(blank=True, null=True, verbose_name='growth % per capita')),
                ('gdp_ppp_constant_2017', models.BigIntegerField(blank=True, null=True, verbose_name='GDP, PPP (constant 2017 international $)')),
                ('gdp_ppp_current', models.BigIntegerField(blank=True, null=True, verbose_name='GDP, PPP (current international $)')),
                ('gdp_constant_2010', models.BigIntegerField(blank=True, null=True, verbose_name='GDP (constant 2010 US$)')),
                ('gdp_current', models.BigIntegerField(blank=True, null=True, verbose_name='GDP (current US$)')),
                ('gdp_percapita_ppp_constant_2017', models.BigIntegerField(blank=True, null=True, verbose_name='GDP per capita, PPP (constant 2017 international $)')),
                ('gdp_percapita_ppp_current', models.BigIntegerField(blank=True, null=True, verbose_name='GDP per capita, PPP (current international $)')),
                ('gdp_percapita_constant_2010', models.BigIntegerField(blank=True, null=True, verbose_name='GDP per capita (constant 2010 US$)')),
                ('gdp_percapita_current', models.BigIntegerField(blank=True, null=True, verbose_name='GDP per capita (current US$)')),
                ('added_by', models.ForeignKey(blank=True, default=None, help_text='User who added the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_countrygdp_adders', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdps', to='places.country', verbose_name='country')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countrygdp', to='sources.source', verbose_name='source')),
                ('updated_by', models.ForeignKey(blank=True, default=None, help_text='User who updated the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_countrygdp_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Country GDP',
                'verbose_name_plural': 'Country GDPs',
                'unique_together': {('country', 'year', 'source')},
            },
        ),
    ]
