# Generated by Django 3.1.1 on 2020-09-20 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('sources', '0001_initial'),
        ('politics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='year')),
                ('change', models.IntegerField(blank=True, null=True, verbose_name='change')),
                ('change_rate', models.FloatField(blank=True, null=True, verbose_name='change %')),
                ('fertility_rate', models.FloatField(blank=True, null=True, verbose_name='fertility')),
                ('median_age', models.FloatField(blank=True, null=True, verbose_name='median age')),
                ('density', models.FloatField(blank=True, null=True, verbose_name='density')),
                ('female', models.BigIntegerField(blank=True, null=True, verbose_name='female')),
                ('male', models.BigIntegerField(blank=True, null=True, verbose_name='male')),
                ('total', models.BigIntegerField(blank=True, null=True, verbose_name='total')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldpopulation', to='sources.source', verbose_name='source')),
            ],
            options={
                'verbose_name': 'World Population',
                'verbose_name_plural': 'World Populations',
                'unique_together': {('year', 'source')},
            },
        ),
        migrations.CreateModel(
            name='InternationalOrganizationPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='year')),
                ('change', models.IntegerField(blank=True, null=True, verbose_name='change')),
                ('change_rate', models.FloatField(blank=True, null=True, verbose_name='change %')),
                ('fertility_rate', models.FloatField(blank=True, null=True, verbose_name='fertility')),
                ('median_age', models.FloatField(blank=True, null=True, verbose_name='median age')),
                ('density', models.FloatField(blank=True, null=True, verbose_name='density')),
                ('female', models.BigIntegerField(blank=True, null=True, verbose_name='female')),
                ('male', models.BigIntegerField(blank=True, null=True, verbose_name='male')),
                ('total', models.BigIntegerField(blank=True, null=True, verbose_name='total')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='politics.internationalorganization', verbose_name='organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internationalorganizationpopulation', to='sources.source', verbose_name='source')),
            ],
            options={
                'verbose_name': 'International Organization Population',
                'verbose_name_plural': 'International Organization Populations',
                'unique_together': {('organization', 'year', 'source')},
            },
        ),
        migrations.CreateModel(
            name='CountryPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='year')),
                ('change', models.IntegerField(blank=True, null=True, verbose_name='change')),
                ('change_rate', models.FloatField(blank=True, null=True, verbose_name='change %')),
                ('fertility_rate', models.FloatField(blank=True, null=True, verbose_name='fertility')),
                ('median_age', models.FloatField(blank=True, null=True, verbose_name='median age')),
                ('density', models.FloatField(blank=True, null=True, verbose_name='density')),
                ('female', models.IntegerField(blank=True, null=True, verbose_name='female')),
                ('male', models.IntegerField(blank=True, null=True, verbose_name='male')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='total')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='places.country', verbose_name='country')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countrypopulation', to='sources.source', verbose_name='source')),
            ],
            options={
                'verbose_name': 'Country Population',
                'verbose_name_plural': 'Country Populations',
                'unique_together': {('country', 'year', 'source')},
            },
        ),
    ]
