# Generated by Django 3.1.1 on 2020-09-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrypopulation',
            old_name='population_female',
            new_name='female',
        ),
        migrations.RenameField(
            model_name='countrypopulation',
            old_name='population_male',
            new_name='male',
        ),
        migrations.RenameField(
            model_name='countrypopulation',
            old_name='population_total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='internationalorganizationpopulation',
            old_name='population_female',
            new_name='female',
        ),
        migrations.RenameField(
            model_name='internationalorganizationpopulation',
            old_name='population_male',
            new_name='male',
        ),
        migrations.RenameField(
            model_name='internationalorganizationpopulation',
            old_name='population_total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='worldpopulation',
            old_name='population_female',
            new_name='female',
        ),
        migrations.RenameField(
            model_name='worldpopulation',
            old_name='population_male',
            new_name='male',
        ),
        migrations.RenameField(
            model_name='worldpopulation',
            old_name='population_total',
            new_name='total',
        ),
    ]
