# Generated by Django 3.1.1 on 2020-09-25 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
        ('sources', '0001_initial'),
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(editable=False, verbose_name='added date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='updated date')),
                ('date', models.DateField(verbose_name='date')),
                ('new_confirmed', models.IntegerField(blank=True, default=0, verbose_name='new confirmed')),
                ('total_confirmed', models.IntegerField(blank=True, default=0, verbose_name='total confirmed')),
                ('new_death', models.IntegerField(blank=True, default=0, verbose_name='new death')),
                ('total_death', models.IntegerField(blank=True, default=0, verbose_name='total death')),
                ('added_by', models.ForeignKey(blank=True, default=None, help_text='User who added the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_covid19_adders', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covid19s', to='places.country', verbose_name='country')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covid19', to='sources.source', verbose_name='source')),
                ('updated_by', models.ForeignKey(blank=True, default=None, help_text='User who updated the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_covid19_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Covid19',
                'verbose_name_plural': 'Covid19',
                'unique_together': {('country', 'date')},
            },
        ),
    ]
