# Generated by Django 3.1.1 on 2020-10-01 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sources', '0001_initial'),
        ('stats', '0002_covid19'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldHdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(editable=False, verbose_name='added date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='updated date')),
                ('year', models.SmallIntegerField(verbose_name='year')),
                ('hdi_value', models.FloatField(verbose_name='hdi')),
                ('added_by', models.ForeignKey(blank=True, default=None, help_text='User who added the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_worldhdi_adders', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worldhdi', to='sources.source', verbose_name='source')),
                ('updated_by', models.ForeignKey(blank=True, default=None, help_text='User who updated the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_worldhdi_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'World HDI',
                'verbose_name_plural': 'World HDI',
                'unique_together': {('year', 'source')},
            },
        ),
        migrations.CreateModel(
            name='CountryHdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(editable=False, verbose_name='added date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='updated date')),
                ('year', models.SmallIntegerField(verbose_name='year')),
                ('hdi_value', models.FloatField(verbose_name='hdi')),
                ('added_by', models.ForeignKey(blank=True, default=None, help_text='User who added the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_countryhdi_adders', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hdis', to='places.country', verbose_name='country')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countryhdi', to='sources.source', verbose_name='source')),
                ('updated_by', models.ForeignKey(blank=True, default=None, help_text='User who updated the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_countryhdi_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Country HDI',
                'verbose_name_plural': 'Country HDIs',
                'unique_together': {('country', 'year', 'source')},
            },
        ),
    ]
