# Generated by Django 3.1.1 on 2020-09-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20200908_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalorganizationpopulation',
            name='total',
            field=models.BigIntegerField(verbose_name='total'),
        ),
    ]
