# Generated by Django 3.1.1 on 2020-09-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20200908_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypopulation',
            name='median_age',
            field=models.FloatField(blank=True, null=True, verbose_name='median age'),
        ),
        migrations.AddField(
            model_name='internationalorganizationpopulation',
            name='median_age',
            field=models.FloatField(blank=True, null=True, verbose_name='median age'),
        ),
        migrations.AddField(
            model_name='worldpopulation',
            name='median_age',
            field=models.FloatField(blank=True, null=True, verbose_name='median age'),
        ),
    ]
