# Generated by Django 3.1.1 on 2020-09-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20200908_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypopulation',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name='density'),
        ),
        migrations.AddField(
            model_name='internationalorganizationpopulation',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name='density'),
        ),
        migrations.AddField(
            model_name='worldpopulation',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name='density'),
        ),
    ]
