# Generated by Django 3.1.1 on 2020-09-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20200908_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrypopulation',
            name='female',
            field=models.IntegerField(blank=True, null=True, verbose_name='female'),
        ),
        migrations.AlterField(
            model_name='countrypopulation',
            name='male',
            field=models.IntegerField(blank=True, null=True, verbose_name='male'),
        ),
        migrations.AlterField(
            model_name='countrypopulation',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='internationalorganizationpopulation',
            name='female',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='female'),
        ),
        migrations.AlterField(
            model_name='internationalorganizationpopulation',
            name='male',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='male'),
        ),
        migrations.AlterField(
            model_name='internationalorganizationpopulation',
            name='total',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='worldpopulation',
            name='female',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='female'),
        ),
        migrations.AlterField(
            model_name='worldpopulation',
            name='male',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='male'),
        ),
        migrations.AlterField(
            model_name='worldpopulation',
            name='total',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='total'),
        ),
    ]
