# Generated by Django 3.1.1 on 2020-09-20 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(editable=False, verbose_name='added date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=245, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('unique_code', models.CharField(blank=True, db_index=True, default='', max_length=9, unique=True, verbose_name='unique code')),
                ('code', models.CharField(blank=True, default='', max_length=250, verbose_name='code')),
                ('short_content', models.TextField(blank=True, default='', help_text='you can give short information.', max_length=250, verbose_name='short content')),
                ('content', models.TextField(blank=True, default='', verbose_name='content')),
                ('meta_title', models.CharField(db_index=True, max_length=245, unique=True, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, default='', max_length=245, verbose_name='meta description')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='publish date')),
                ('unpublish_at', models.DateTimeField(blank=True, null=True, verbose_name='unpublish date')),
                ('is_published', models.BooleanField(default=False, editable=False, verbose_name='is published')),
                ('organization_type', models.CharField(choices=[('UIGO', 'Umbrella Intergovernmental organization'), ('IGO', 'Intergovernmental organization'), ('INGO', 'International non-governmental organization'), ('OR', 'Organ'), ('CO', 'Convention'), ('PR', 'Programme'), ('SA', 'Statistical Area')], default='OR', max_length=4, verbose_name='type')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('headquarters', models.CharField(blank=True, default='', max_length=100, verbose_name='headquarters')),
                ('established_at', models.DateField(blank=True, null=True, verbose_name='established at')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
                ('iso_numeric', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ISO numeric')),
                ('added_by', models.ForeignKey(blank=True, default=None, help_text='User who added the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politics_internationalorganization_adders', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='politics.internationalorganization', verbose_name='parent')),
                ('updated_by', models.ForeignKey(blank=True, default=None, help_text='User who updated the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politics_internationalorganization_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'International Organization',
                'verbose_name_plural': 'International Organizations',
            },
        ),
        migrations.CreateModel(
            name='LocalOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(editable=False, verbose_name='added date')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=245, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('unique_code', models.CharField(blank=True, db_index=True, default='', max_length=9, unique=True, verbose_name='unique code')),
                ('code', models.CharField(blank=True, default='', max_length=250, verbose_name='code')),
                ('short_content', models.TextField(blank=True, default='', help_text='you can give short information.', max_length=250, verbose_name='short content')),
                ('content', models.TextField(blank=True, default='', verbose_name='content')),
                ('meta_title', models.CharField(db_index=True, max_length=245, unique=True, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, default='', max_length=245, verbose_name='meta description')),
                ('publish_at', models.DateTimeField(blank=True, null=True, verbose_name='publish date')),
                ('unpublish_at', models.DateTimeField(blank=True, null=True, verbose_name='unpublish date')),
                ('is_published', models.BooleanField(default=False, editable=False, verbose_name='is published')),
                ('organization_type', models.CharField(choices=[('UIGO', 'Umbrella Intergovernmental organization'), ('IGO', 'Intergovernmental organization'), ('INGO', 'International non-governmental organization'), ('OR', 'Organ'), ('CO', 'Convention'), ('PR', 'Programme'), ('SA', 'Statistical Area')], default='OR', max_length=4, verbose_name='type')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('headquarters', models.CharField(blank=True, default='', max_length=100, verbose_name='headquarters')),
                ('established_at', models.DateField(blank=True, null=True, verbose_name='established at')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
                ('added_by', models.ForeignKey(blank=True, default=None, help_text='User who added the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politics_localorganization_adders', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='politics.localorganization', verbose_name='parent')),
                ('updated_by', models.ForeignKey(blank=True, default=None, help_text='User who updated the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='politics_localorganization_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Local Organization',
                'verbose_name_plural': 'Local Organizations',
            },
        ),
        migrations.CreateModel(
            name='InternationalOrganizationMemberships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('M', 'Member'), ('O', 'Observer'), ('T', 'Temporary'), ('AA', 'Approval'), ('AP', 'Acceptance'), ('AS', 'Accession'), ('SU', 'Succession'), ('R', 'Ratification')], default='M', max_length=2, verbose_name='type')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='started at')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='ended at')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membershipinternationalorganizations', to='places.country', verbose_name='country')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membershipinternationalorganizations', to='politics.internationalorganization', verbose_name='organization')),
            ],
        ),
    ]
